//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminTEmplate.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserDeatil
    {
        public int Id { get; set; }
        public string Username { get; set; }
        public string Gender { get; set; }
        public Nullable<System.DateTime> Brithday { get; set; }
        public Nullable<double> Height { get; set; }
        public Nullable<double> Veight { get; set; }
        public string Mail { get; set; }
        public string Number { get; set; }
        public string Adress { get; set; }
        public string Stattus { get; set; }
    }
}
